[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cms"
version = "1.0.0"
description = "A simple Rubik's Cube Simulator developed using magiccube, TDD and pytest."
authors = [
    {name = "Steve Smythe", email = "steve@smythefamily.com"},
]
dependencies = []

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
pythonpath = ["src"]

[tool.poetry.scripts]
cube = "cms.main:main"
